name: Gitstamp for GitHub Actions
author: Arto Bendiken
description: Timestamp your Git commits using the Arweave permaweb.
inputs:
  wallet-key:
    description: The Arweave wallet key to use for signing transactions.
    required: true
  commit-link:
    description: A boolean indicating whether to include a GitHub commit link.
    required: false
    default: false
outputs:
  transaction-id:
    description: The Arweave transaction ID.
  transaction-link:
    description: The Arweave transaction explorer link on ViewBlock.io.
  response-code:
    description: The Arweave HTTP API response status code.
  response-text:
    description: The Arweave HTTP API response status text.
runs:
  using: node16
  main: index.js
branding:
  icon: clock
  color: gray-dark
